### ISSUE TITLE
Hi, im interested in your work, but how to get the segments folder？ Thanks! 

### ISSUE THREAD

**Issue by wangjiakun13** [VITA-Group/NeRF-SOS#1]

**Comment by zhiwenfan** [comment]
Hi, you can download via this link: https://drive.google.com/file/d/1gD5paJ8HBOFVyMRgweTc0jNTL41SmBFz/view?usp=sharing

**Comment by zhiwenfan** [comment]
Hi, you can now run scripts/eval.sh to obtain the evaluation results with a pre-trained ckpt.

**Comment by wangjiakun13** [comment]
> Hi, you can now run scripts/eval.sh to obtain the evaluation results with a pre-trained ckpt.

Thanks a lot，Great work😊！
